name: Build and Publish Container Image

on:
  schedule:
    # Runs every day at 00:00 UTC. Adjust cron syntax as needed.
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          repository: 'VijayAdithyaBK/maarkdown-viewer'
          ref: 'gh-pages'
          fetch-depth: 1

      - name: Set Variables
        id: variables
        run: |
          echo "[INFO] Converting everything to lowercase because ghcr repository name must be lowercase..."
          ACTOR="$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')"
          echo "actor=$ACTOR" >>$GITHUB_OUTPUT
          REPOSITORY="$(echo "${{ github.repository }}" | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')"
          echo "repository=$REPOSITORY" >>$GITHUB_OUTPUT
          echo "[INFO] Getting Latest Commit Hash..."
          COMMIT_HASH="$(git rev-parse --short HEAD)"
          echo "last_commit=$COMMIT_HASH" >>$GITHUB_OUTPUT
          echo "[INFO] Found latest commit hash: $COMMIT_HASH"
          echo "[INFO] Checking if Image Tag Exists in GHCR..."
          TAG="ghcr.io/$ACTOR/$REPOSITORY:$COMMIT_HASH"
          if docker manifest inspect "$TAG" > /dev/null 2>&1; then
            echo "[INFO] Image tag $TAG already exists. Skipping build..."
            echo "imageexists=true" >> $GITHUB_OUTPUT
          else
            echo "[INFO] Image tag $TAG not found. Proceeding with build..."
            echo "imageexists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Containerfile
        if: steps.variables.outputs.imageexists == 'false'
        run: |
          cat <<EOF > .dockerignore
          .git/
          .git
          EOF
          cat <<EOF > Containerfile
          FROM nginx:latest
          RUN rm -r /usr/share/nginx/html
          COPY . /usr/share/nginx/html
          EXPOSE 80
          CMD ["nginx", "-g", "daemon off;"]
          EOF

      - name: Set up Docker Buildx
        if: steps.variables.outputs.imageexists == 'false'
        uses: docker/setup-buildx-action@v4

      - name: Login to GitHub Container Registry
        if: steps.variables.outputs.imageexists == 'false'
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Container Image
        if: steps.variables.outputs.imageexists == 'false'
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Containerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ steps.variables.outputs.actor }}/${{ steps.variables.outputs.repository }}:${{ steps.variables.outputs.last_commit }}
            ghcr.io/${{ steps.variables.outputs.actor }}/${{ steps.variables.outputs.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
